
package Vista;
import Controlador.AcomodarImagen;
import javax.swing.*;
import Modelo.Entidades.Proyecto;
import Modelo.DAO.ProyectoDAO;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author emili
 */
public class agregarProyecto extends javax.swing.JPanel {
    private final AcomodarImagen acomodarImagen = new AcomodarImagen();
    CardLayout card;
    private JPanel panelContainer;
    private vistaProyectos panelProyectos;

    /**
     * Creates new form agregarProyecto
     */
    public agregarProyecto(CardLayout layout, JPanel container, vistaProyectos panelProyectos) {
        initComponents();
        
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setEditable(true);
        txtDescripcion.setOpaque(false);
        txtDescripcion.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jPanel1.setPreferredSize(new Dimension(284, 520));
        this.setPreferredSize(jPanel1.getPreferredSize());
        this.card = layout;
        this.panelContainer = container;
        this.panelProyectos = panelProyectos;
            
            cargarEmpresasEnCombo();
     
       
    }
    
    public agregarProyecto() {
    initComponents();
    this.card = new CardLayout(); // puedes dejarlo dummy
    this.panelContainer = new JPanel(card);
    this.panelProyectos = null; // no se usará en modo ventana
    cargarEmpresasEnCombo();
}
private void agregarProyecto() {
    String nombre = txtNombre.getText().trim();
    String descripcion = txtDescripcion.getText().trim();
    EmpresaItem empresaSeleccionada = (EmpresaItem) empresasBox.getSelectedItem();

    // Validaciones
    if (nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ El nombre del proyecto no puede estar vacío.");
        return;
    }
    if (descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ La descripción no puede estar vacía.");
        return;
    }
    if (empresaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "⚠️ Debes seleccionar una empresa.");
        return;
    }

    // Validación: evitar nombre duplicado
    ProyectoDAO dao = new ProyectoDAO();
    boolean existe = dao.existeNombreProyecto(nombre);
    if (existe) {
        JOptionPane.showMessageDialog(this, "❌ Ya existe un proyecto con ese nombre.");
        return;
    }

    // Insertar proyecto
    Proyecto proyecto = new Proyecto();
    proyecto.setNombre(nombre);
    proyecto.setDescripcion(descripcion);
    proyecto.setIdEmpresa(empresaSeleccionada.getId());
    proyecto.setEstatus("Disponible");
boolean resultado = dao.agregarProyecto(proyecto);
if (resultado) {
    JOptionPane.showMessageDialog(this, "✅ Proyecto agregado exitosamente.");
    txtNombre.setText("");
    txtDescripcion.setText("");

    // Actualizar tabla de proyectos si fue embebido
    if (panelProyectos != null) {
        panelProyectos.mostrarProyectosEnTabla();
    }

    // Verificar si se abrió como ventana externa o desde CardLayout
    java.awt.Window ventana = SwingUtilities.getWindowAncestor(this);
    if (ventana instanceof JFrame && panelProyectos == null) {
        ventana.dispose(); // ✅ Cierra la ventana si es externa
    } else {
        // ✅ Cambia al panel de proyectos si está embebido
        card.show(panelContainer, "panelProyectos");
        ajustarVentana();
    }

} else {
    JOptionPane.showMessageDialog(this, "❌ Error al agregar el proyecto.");
}
    
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        empresasBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 157, 35));
        jPanel2.add(empresasBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 157, 30));

        jLabel1.setText("Nombre del Proyecto:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel2.setText("Empresa:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("Descripcion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 130));

        jButton4.setText("Atras");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agregarProyecto();
        //panelProyectos.cargarDatos();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
       private void ajustarVentana() {
    java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (ventana instanceof javax.swing.JFrame) {
        ((javax.swing.JFrame) ventana).pack();
        ventana.setLocationRelativeTo(null);
    }
}
       private static class EmpresaItem {
    private int id;
    private String nombre;

    public EmpresaItem(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public int getId() {
        return id;
    }

    @Override
    public String toString() {
        return nombre;
    }
}

       
       
       public static void cargarEmpresasEnCombo() {
    empresasBox.removeAllItems();
    String sql = "SELECT id_empresa, nombre FROM empresa";
    try (java.sql.Connection conn = Utilidades.Conexion.getConexion();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {
        while (rs.next()) {
            EmpresaItem item = new EmpresaItem(rs.getInt("id_empresa"), rs.getString("nombre"));
            empresasBox.addItem(item);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
       
   public void recargarEmpresas() {
    cargarEmpresasEnCombo();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<EmpresaItem> empresasBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
