/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.AcomodarImagen;
import Modelo.DAO.AlumnoCarg;
import Modelo.DAO.AlumnoDAO;
import Utilidades.Conexion;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.awt.Cursor;
import java.awt.Desktop;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;


/**
 *
 * @author yahir
 */
public class AgregarAnteproyecto extends javax.swing.JPanel {
private final AcomodarImagen acomodarImagen = new AcomodarImagen();
private File archivoTemporalPDF;
    private final OpcionAnteproyecto panelPadre;

    /**
     * Creates new form AgregarAnteproyecto
     */
    public AgregarAnteproyecto(OpcionAnteproyecto padre) {
        this.panelPadre = padre;
        initComponents();
         txtNombreAnteproyecto.addActionListener(e -> txtNombreEmpresa.requestFocus());
    txtNombreEmpresa.addActionListener(e -> txtTelefono.requestFocus());
    txtTelefono.addActionListener(e -> txtDireccion.requestFocus());
    txtDireccion.addActionListener(e -> txtCorreo.requestFocus());
    txtCorreo.addActionListener(e -> txtRFC.requestFocus());
    txtRFC.addActionListener(e -> txtDescripcion.requestFocus());
        BtnElegirAnteProyectoBanco.setEnabled(false);
        actualizarTablaAlumnos(tablaAlumnos);
        tablaAlumnos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/backbutton.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        JPanelBack.setIcon(new ImageIcon(imagenRedimensionada));
        JPanelBack.setBorderPainted(false);
        JPanelBack.setContentAreaFilled(false);
        JPanelBack.setFocusPainted(false);     
        JPanelBack.setOpaque(false);
        
        JLabelDocumentoCargado.setText("📄 No hay documento cargado");
        JLabelDocumentoCargado.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        JLabelDocumentoCargado.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (archivoTemporalPDF != null && archivoTemporalPDF.exists()) {
                    try {
                        Desktop.getDesktop().open(archivoTemporalPDF);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "No se pudo abrir el documento.");
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreAnteproyecto = new javax.swing.JTextField();
        BntCargarPDF = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        BtnElegirAnteProyectoBanco = new javax.swing.JButton();
        ComboBoxElegir = new javax.swing.JComboBox<>();
        JLabelDocumentoCargado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanelBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(null);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO DE CONTROL", "NOMBRE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaAlumnos.setSelectionBackground(new java.awt.Color(0, 83, 188));
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlumnos);

        jLabel4.setText("Nombre del Anteproyecto");

        BntCargarPDF.setBackground(new java.awt.Color(0, 153, 255));
        BntCargarPDF.setForeground(new java.awt.Color(255, 255, 255));
        BntCargarPDF.setText("⬆️ Cargar Documento ⬆️");
        BntCargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntCargarPDFActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("EMPRESA"));

        jLabel6.setText("RFC");

        jLabel7.setText("Correo");

        jLabel8.setText("Direccion");

        jLabel9.setText("Telefono");

        jLabel10.setText("Nombre");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel5.setText("DESCRIPCION");

        txtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCorreo)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtRFC, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        BtnGuardar.setBackground(new java.awt.Color(0, 153, 255));
        BtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BtnGuardar.setText("GUARDAR ANTEPROYECTO");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnElegirAnteProyectoBanco.setText("ELEGIR ANTEPROYECTO");
        BtnElegirAnteProyectoBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnElegirAnteProyectoBancoMouseClicked(evt);
            }
        });

        ComboBoxElegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGREGAR NUEVO ANTEPROYECTO", "ELEGIR DEL BANCO DE PROYECTOS" }));
        ComboBoxElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxElegirActionPerformed(evt);
            }
        });

        JLabelDocumentoCargado.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ComboBoxElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(BtnElegirAnteProyectoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addComponent(txtNombreAnteproyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BntCargarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(JLabelDocumentoCargado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnElegirAnteProyectoBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BntCargarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelDocumentoCargado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo Anteproyecto");

        JPanelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backbutton.png"))); // NOI18N
        JPanelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanelBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("SELECCIONA A UN ALUMNO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
    }//GEN-LAST:event_tablaAlumnosMouseClicked
    
    void actualizarTablaAlumnos(JTable tablaAlumnos) {
         AlumnoDAO dao = new AlumnoDAO();
        List<AlumnoCarg> lista = dao.obtenerTodosLosAlumnos();
        DefaultTableModel model = (DefaultTableModel) tablaAlumnos.getModel();
        model.setRowCount(0);

        for (AlumnoCarg a : lista) {
            String nombreCompleto = a.getNombre() + " " + a.getApellidoPaterno() + " " + a.getApellidoMaterno();
            model.addRow(new Object[]{a.getNumeroControl(), nombreCompleto});
        }
    }
    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked

    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void JPanelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPanelBackActionPerformed
    Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_JPanelBackActionPerformed

    private void BntCargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntCargarPDFActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona un archivo PDF o Word");

        int resultado = fileChooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            archivoTemporalPDF = fileChooser.getSelectedFile();
            String nombre = archivoTemporalPDF.getName().toLowerCase();

            if (!nombre.endsWith(".pdf") && !nombre.endsWith(".doc") && !nombre.endsWith(".docx")) {
                JOptionPane.showMessageDialog(this, "Solo se permiten archivos PDF o Word.");
                archivoTemporalPDF = null;
                JLabelDocumentoCargado.setText("📄 No hay documento cargado");
                return;
            }

            JLabelDocumentoCargado.setText("📎 " + archivoTemporalPDF.getName());
            JOptionPane.showMessageDialog(this, "✔️ Documento cargado. Haz clic para visualizar.");
        }
    }//GEN-LAST:event_BntCargarPDFActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
     String nombre = txtNombreAnteproyecto.getText().trim().toUpperCase();
    String descripcion = txtDescripcion.getText().trim();
    String lineaInvestigacion = txtNombreEmpresa.getText().trim(); // Renómbralo si no es línea
    String estado = "Anteproyecto";
    String usuario = System.getProperty("user.name");
    String rfcEmpresa = txtRFC.getText().trim().toUpperCase();
    String telefono = txtTelefono.getText().trim();
    String correo = txtCorreo.getText().trim();

    if (nombre.isEmpty() || descripcion.isEmpty() || lineaInvestigacion.isEmpty() || rfcEmpresa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Completa todos los campos obligatorios.");
        return;
    }

    if (!telefono.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Número de teléfono inválido. Debe tener 10 dígitos.");
        return;
    }

    if (!correo.matches("^[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,}$")) {
        JOptionPane.showMessageDialog(this, "Correo electrónico inválido.");
        return;
    }

    int[] filas = tablaAlumnos.getSelectedRows();
    if (filas.length == 0 || filas.length > 3) {
        JOptionPane.showMessageDialog(this, "Selecciona entre 1 y 3 alumnos.");
        return;
    }

    if (archivoTemporalPDF == null || !archivoTemporalPDF.exists()) {
        JOptionPane.showMessageDialog(this, "Carga un documento válido antes de guardar.");
        return;
    }

    try (Connection conn = Conexion.getConexion()) {
        boolean ok = true;

        for (int fila : filas) {
            String nControl = tablaAlumnos.getValueAt(fila, 0).toString();
            int idAlumno = new Modelo.DAO.AlumnoDAO().consultarIdPorControl(nControl);

            PreparedStatement ps = conn.prepareStatement(
                "INSERT INTO anteproyecto (nombre, descripcion, linea_investigacion, estado, fecha_registro, usuario_registro, fk_alumno, rfc_empresa) " +
                "VALUES (?, ?, ?, ?, NOW(), ?, ?, ?)"
            );
            ps.setString(1, nombre);
            ps.setString(2, descripcion);
            ps.setString(3, lineaInvestigacion);
            ps.setString(4, estado);
            ps.setString(5, usuario);
            ps.setInt(6, idAlumno);
            ps.setString(7, rfcEmpresa);

            int result = ps.executeUpdate();
            if (result == 0) {
                System.out.println("⚠️ No se insertó anteproyecto para alumno: " + nControl);
                ok = false;
            }
        }

        // 💾 Guardar PDF localmente
        String rutaFinal = System.getProperty("user.home") + "/Documents/AnteproyectosCargados/";
        File carpeta = new File(rutaFinal);
        if (!carpeta.exists()) carpeta.mkdirs();

        File destino = new File(carpeta, archivoTemporalPDF.getName());
        Files.copy(archivoTemporalPDF.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);

        if (ok) {
            JOptionPane.showMessageDialog(this, "✅ Anteproyecto guardado correctamente.");
            panelPadre.actualizarTablaAnteproyectos();
            Window ventana = SwingUtilities.getWindowAncestor(this);
            if (ventana != null) ventana.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Falló al guardar algunos registros. Revisa la consola.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error técnico al guardar: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_BtnGuardarActionPerformed
   
    private void ComboBoxElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxElegirActionPerformed
     String opcionSeleccionada = (String) ComboBoxElegir.getSelectedItem();

    if ("AGREGAR NUEVO ANTEPROYECTO".equals(opcionSeleccionada)) {
        BtnElegirAnteProyectoBanco.setEnabled(false);

        // Desbloquea todos los campos
        txtNombreAnteproyecto.setEditable(true);
        txtNombreEmpresa.setEditable(true);
        txtTelefono.setEditable(true);
        txtDireccion.setEditable(true);
        txtCorreo.setEditable(true);
        txtRFC.setEditable(true);
        
        txtNombreAnteproyecto.setText("");
        txtNombreEmpresa.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtRFC.setText("");
        txtDescripcion.setText("");
        JLabelDocumentoCargado.setText("📄 No hay documento cargado");
        archivoTemporalPDF = null;
    } else if ("ELEGIR DEL BANCO DE PROYECTOS".equals(opcionSeleccionada)) {
        BtnElegirAnteProyectoBanco.setEnabled(true);

        // Bloquea campos excepto los permitidos
        txtNombreAnteproyecto.setEditable(false);
        txtNombreEmpresa.setEditable(false);
        txtTelefono.setEditable(false);
        txtDireccion.setEditable(false);
        txtCorreo.setEditable(false);
        txtRFC.setEditable(false);
        txtDescripcion.setEditable(true);
        BntCargarPDF.setEnabled(true);

        // Limpia campos visibles
        txtNombreAnteproyecto.setText("");
        txtNombreEmpresa.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtRFC.setText("");
        txtDescripcion.setText("");
        JLabelDocumentoCargado.setText("📄 No hay documento cargado");
        archivoTemporalPDF = null;

        tablaAlumnos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }
    }//GEN-LAST:event_ComboBoxElegirActionPerformed

    private void txtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaActionPerformed
    
    
    private void BtnElegirAnteProyectoBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnElegirAnteProyectoBancoMouseClicked
       String opcionSeleccionada = (String) ComboBoxElegir.getSelectedItem();
    if (!"ELEGIR DEL BANCO DE PROYECTOS".equals(opcionSeleccionada)) {
        JOptionPane.showMessageDialog(null, "Esta opción no está disponible en el modo actual.");
        return;
    }
        JFrame ventanaAgregar = new JFrame();
        ventanaAgregar.setUndecorated(true);
    AnteproyectoBanco panelBanco = new AnteproyectoBanco(this);
    ventanaAgregar.setContentPane(panelBanco);
    ventanaAgregar.setSize(400,400); //ancho - largo
    ventanaAgregar.setLocationRelativeTo(null); 
    ventanaAgregar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventanaAgregar.setVisible(true);

    }//GEN-LAST:event_BtnElegirAnteProyectoBancoMouseClicked
    public void rellenarCamposDesdeBanco(String nombreProyecto, String estatus,
    String nombreEmpresa, String direccion, String telefono,
    String correo, String rfc) {

    txtNombreAnteproyecto.setEditable(true);
    txtDescripcion.setEditable(true);
    txtNombreEmpresa.setEditable(true);
    txtDireccion.setEditable(true);
    txtTelefono.setEditable(true);
    txtCorreo.setEditable(true);
    txtRFC.setEditable(true);

    txtNombreAnteproyecto.setText(nombreProyecto);
    txtDescripcion.setText("");
    txtNombreEmpresa.setText(nombreEmpresa);
    txtDireccion.setText(direccion);
    txtTelefono.setText(telefono);
    txtCorreo.setText(correo);
    txtRFC.setText(rfc);

    txtNombreAnteproyecto.setEditable(false);
    txtDescripcion.setEditable(true);
    txtNombreEmpresa.setEditable(false);
    txtDireccion.setEditable(false);
    txtTelefono.setEditable(false);
    txtCorreo.setEditable(false);
    txtRFC.setEditable(false);

    JLabelDocumentoCargado.setText("Cargado desde el banco de proyectos");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntCargarPDF;
    private javax.swing.JButton BtnElegirAnteProyectoBanco;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> ComboBoxElegir;
    private javax.swing.JLabel JLabelDocumentoCargado;
    private javax.swing.JButton JPanelBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombreAnteproyecto;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtRFC;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
