/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.AcomodarImagen;
import Modelo.DAO.EmpresaDAO;
import Modelo.DAO.ProyectoDAO;
import Modelo.Entidades.EmpresaEntidad;
import Modelo.Entidades.Proyecto;
import Utilidades.Conexion;
import java.awt.Image;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yahir
 */
public class AnteproyectoBanco extends javax.swing.JPanel {
private final AcomodarImagen acomodarImagen = new AcomodarImagen();
private final AgregarAnteproyecto panelPadre;
    /**
     * Creates new form AnteproyectoBanco
     */
    public AnteproyectoBanco(AgregarAnteproyecto padre) {
         this.panelPadre = padre;
        initComponents();
        mostrarProyectosEnTabla();
        ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/backbutton.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        JPanelBack.setIcon(new ImageIcon(imagenRedimensionada));
        JPanelBack.setBorderPainted(false);
        JPanelBack.setContentAreaFilled(false);
        JPanelBack.setFocusPainted(false);     
        JPanelBack.setOpaque(false);
    }
  public void mostrarProyectosEnTabla() {
            DefaultTableModel modelo = (DefaultTableModel) tablaProyectos.getModel();
            modelo.setRowCount(0); 

            ProyectoDAO dao = new ProyectoDAO();
            List<Proyecto> lista = dao.obtenerTodos();

            for (Proyecto p : lista) {
                String nombreEmpresa = obtenerNombreEmpresa(p.getIdEmpresa());
                modelo.addRow(new Object[]{
                p.getNombre(),
                p.getEstatus(),
                nombreEmpresa
            });
            }
            System.out.println("✅ Se cargaron " + lista.size() + " proyectos.");
        }
    private boolean anteproyectoExiste(String nombreAnteproyecto) {
    String sql = "SELECT COUNT(*) FROM anteproyecto WHERE nombre = ?";
    try (Connection conn = Conexion.getConexion();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, nombreAnteproyecto.toUpperCase());
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1) > 0;
        }
    } catch (SQLException e) {
        System.out.println("[ERROR] Validación de existencia falló: " + e.getMessage());
    }
    return false;
    }
     private String obtenerNombreEmpresa(int idEmpresa) {
            String nombre = "";
            String sql = "SELECT nombre FROM empresa WHERE id_empresa = ?";

            try (Connection conn = Conexion.getConexion();
                 PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setInt(1, idEmpresa);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    nombre = rs.getString("nombre");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            return nombre;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanelBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        BtnAceptarBanco = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Banco de Anteproyectos");

        JPanelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backbutton.png"))); // NOI18N
        JPanelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanelBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Estatus", "Empresa"
            }
        ));
        tablaProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProyectosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProyectosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProyectos);

        BtnAceptarBanco.setText("ACEPTAR");
        BtnAceptarBanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarBancoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(BtnAceptarBanco)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAceptarBanco)
                .addGap(0, 17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JPanelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPanelBackActionPerformed
        Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_JPanelBackActionPerformed

    private void tablaProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProyectosMouseClicked

    }//GEN-LAST:event_tablaProyectosMouseClicked

    private void tablaProyectosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProyectosMousePressed
        int fila = tablaProyectos.getSelectedRow();
        if (fila == -1) return;

        String nombre = tablaProyectos.getValueAt(fila, 0).toString();
        String estatus = tablaProyectos.getValueAt(fila, 1).toString(); 
        String empresa = tablaProyectos.getValueAt(fila, 2).toString();  
    }//GEN-LAST:event_tablaProyectosMousePressed

    private void BtnAceptarBancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarBancoMouseClicked
       int fila = tablaProyectos.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un anteproyecto del banco.");
        return;
    }

    String nombreProyecto = tablaProyectos.getValueAt(fila, 0).toString().trim();

    Proyecto proyecto = new ProyectoDAO().buscarPorNombre(nombreProyecto);
    if (proyecto == null) {
        JOptionPane.showMessageDialog(this, "⚠️ Proyecto no encontrado.");
        return;
    }
    
    if (anteproyectoExiste(nombreProyecto)) {
        JOptionPane.showMessageDialog(this, "⚠️ El anteproyecto '" + nombreProyecto + "' ya ha sido registrado.");
        return;
    }

    EmpresaDAO dao = new EmpresaDAO();
    EmpresaEntidad original = dao.buscarPorId(proyecto.getIdEmpresa());
    EmpresaEntidad empresa = normalizarEmpresa(original);

    panelPadre.rellenarCamposDesdeBanco(
        proyecto.getNombre(),
        proyecto.getEstatus(),
        empresa.getNombre(),
        empresa.getDireccion(),
        empresa.getContacto(), 
        empresa.getCorreo(),
        empresa.getRfc()
    );

    Window ventana = SwingUtilities.getWindowAncestor(this);
    if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_BtnAceptarBancoMouseClicked
    private EmpresaEntidad normalizarEmpresa(EmpresaEntidad original) {
    EmpresaEntidad e = new EmpresaEntidad();
    e.setIdEmpresa(original.getIdEmpresa());
    e.setNombre(original.getNombre().trim());
    e.setContacto(original.getContacto().trim());

    String correo = original.getCorreo().trim().toLowerCase();
    if (!correo.matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
        correo = "correo@invalido.com";
    }
    e.setCorreo(correo);

    e.setRfc(original.getRfc().trim().toUpperCase()); 
    e.setDireccion(original.getDireccion().trim());

    return e;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptarBanco;
    private javax.swing.JButton JPanelBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaProyectos;
    // End of variables declaration//GEN-END:variables
}
