/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.AcomodarImagen;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author emili
 */
public class editarProyecto extends javax.swing.JPanel {
       private final AcomodarImagen acomodarImagen = new AcomodarImagen();
       CardLayout card;
       private JPanel panelContainer;
       private int idProyecto; 
       private vistaProyectos panelProyectos;
       private String estatusActual;
       
         

      

    public editarProyecto(CardLayout layout, JPanel container, vistaProyectos panelProyectos) {
        initComponents();
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setEditable(true);
        txtDescripcion.setOpaque(false);
        txtDescripcion.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        

        //panelProyectos.mostrarProyectosEnTabla();
        this.card = layout;
        this.panelContainer = container;
        this.panelProyectos = panelProyectos;
        setPreferredSize(new Dimension(235, 380)); // Ajusta según tu diseño ideal
        revalidate();
        repaint();
         acomodarImagen.configurarPanelConImagen("/img/ITOlogo.png", JPanelLOGO);  
         JPanelLOGO.setOpaque(false);
         JPanelLOGO.setBorder(null);
         JPanelLOGO.setBackground(new Color(0,0,0,0));
         this.setVisible(true);
        
         acomodarImagen.configurarPanelConImagen("/img/backbutton.png", JPanelBack);  
         JPanelBack.setOpaque(false);
         JPanelBack.setBorder(null);
         JPanelBack.setBackground(new Color(0,0,0,0));
         this.setVisible(true);
         
         empresasBox.removeAllItems();
            String sql = "SELECT id_empresa, nombre FROM empresa";

            try (java.sql.Connection conn = Utilidades.Conexion.getConexion();
                 java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                 java.sql.ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    EmpresaItem item = new EmpresaItem(rs.getInt("id_empresa"), rs.getString("nombre"));
                    empresasBox.addItem(item);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        empresasBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        JPanelLOGO = new javax.swing.JPanel();
        JPanelBack = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(235, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(235, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        empresasBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        jLabel1.setText("Nombre del Proyecto:");

        jLabel2.setText("Empresa:");

        jLabel3.setText("Descripcion:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(empresasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empresasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 400, 330));

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        JPanelLOGO.setBackground(new java.awt.Color(255, 255, 255));
        JPanelLOGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelLOGO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(JPanelLOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 90, 90));

        JPanelBack.setBackground(new java.awt.Color(255, 255, 255));
        JPanelBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPanelBackMouseClicked(evt);
            }
        });
        JPanelBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(JPanelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    
    String nombre = txtNombre.getText().trim();
    String descripcion = txtDescripcion.getText().trim();
    EmpresaItem empresaSeleccionada = (EmpresaItem) empresasBox.getSelectedItem();

    if (empresaSeleccionada == null || nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠️ Nombre y empresa son obligatorios.");
        return;
    }

    // Validar si existe otro proyecto con ese nombre
    Modelo.DAO.ProyectoDAO dao = new Modelo.DAO.ProyectoDAO();
    boolean nombreDuplicado = dao.existeNombreProyectoConOtroId(nombre, idProyecto);
    if (nombreDuplicado) {
        JOptionPane.showMessageDialog(this, "❌ Ya existe otro proyecto con ese nombre.");
        return;
    }

    // Continuar con la actualización
    int idEmpresa = empresaSeleccionada.getId();
    Modelo.Entidades.Proyecto proyecto = new Modelo.Entidades.Proyecto();
    proyecto.setIdProyecto(idProyecto);
    proyecto.setNombre(nombre);
    proyecto.setDescripcion(descripcion);
    proyecto.setIdEmpresa(idEmpresa);
    proyecto.setEstatus(estatusActual);
    

    boolean actualizado = dao.actualizarProyecto(proyecto);
    if (actualizado) {
        JOptionPane.showMessageDialog(this, "✅ Proyecto actualizado correctamente.");

        // Recargar tabla
        if (panelProyectos != null) {
            panelProyectos.mostrarProyectosEnTabla();
        }

        card.show(panelContainer, "panelProyectos");
        ajustarVentana();
    } else {
        JOptionPane.showMessageDialog(this, "❌ Error al actualizar el proyecto.");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void JPanelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPanelBackMouseClicked
        // TODO add your handling code here:
        card.show(panelContainer, "panelProyectos");
        ajustarVentana();
    }//GEN-LAST:event_JPanelBackMouseClicked

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

          private void ajustarVentana() {
            java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (ventana instanceof javax.swing.JFrame) {
                ((javax.swing.JFrame) ventana).pack();
                ventana.setLocationRelativeTo(null);
            }
        }
          
          
                public void cargarDatos(int id, String nombre, String empresaNombre, String descripcion, String estatus) {
            this.idProyecto = id;
            txtNombre.setText(nombre);
            txtDescripcion.setText(descripcion);
            this.estatusActual = estatus; 
            

            // Seleccionar empresa por nombre
            for (int i = 0; i < empresasBox.getItemCount(); i++) {
                EmpresaItem item = (EmpresaItem) empresasBox.getItemAt(i);
                if (item.toString().equals(empresaNombre)) {
                    empresasBox.setSelectedIndex(i);
                    break;
                }
            }
        }

                    private static class EmpresaItem {
              private int id;
              private String nombre;

              public EmpresaItem(int id, String nombre) {
                  this.id = id;
                  this.nombre = nombre;
              }

              public int getId() {
                  return id;
              }

              @Override
              public String toString() {
                  return nombre;
              }
          }


          

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBack;
    private javax.swing.JPanel JPanelLOGO;
    private javax.swing.JComboBox<EmpresaItem> empresasBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
