/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JPanel;
import Controlador.AcomodarImagen;
import Modelo.DAO.DocenteCarg;
import Modelo.DAO.DocenteDAO;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author yahir
 */
public class OpcionDocentes extends javax.swing.JPanel {
private final AcomodarImagen acomodarImagen = new AcomodarImagen();
    /**
     * Creates new form OpcionDocentes
     */
    CardLayout card;
    private JPanel panelContainer;
    public OpcionDocentes(CardLayout layout, JPanel container) {
        this.card = layout;
    this.panelContainer = container;
    this.setPreferredSize(new Dimension(1000, 650));
        initComponents();
        actualizarTablaDocentes();
        txtIngresarRfc.getDocument().addDocumentListener(new DocumentListener() {
    public void insertUpdate(DocumentEvent e) { filtrarRFC(); }
    public void removeUpdate(DocumentEvent e) { filtrarRFC(); }
    public void changedUpdate(DocumentEvent e) { filtrarRFC(); }
});

    acomodarImagen.configurarPanelConImagen("/img/ITOlogo.png", JPanelLOGO);  
    JPanelLOGO.setOpaque(false);
    JPanelLOGO.setBorder(null);
    JPanelLOGO.setBackground(new Color(0,0,0,0));
    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/backbutton.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        JPanelBack.setIcon(new ImageIcon(imagenRedimensionada));
        JPanelBack.setBorderPainted(false);         // sin borde
        JPanelBack.setContentAreaFilled(false);     // sin fondo gris
        JPanelBack.setFocusPainted(false);          // sin borde de enfoque
        JPanelBack.setOpaque(false); 
    }
    public void actualizarTablaDocentes() {
        DefaultTableModel modelo = (DefaultTableModel) tablaDocentex.getModel();
        modelo.setRowCount(0);

        List<DocenteCarg> lista = new DocenteDAO().obtenerTodos();
        for (DocenteCarg d : lista) {
            String nombreCompleto = d.getNombre() + " " + d.getApellidoPaterno() + " " + d.getApellidoMaterno();
            modelo.addRow(new Object[]{d.getRfc(), nombreCompleto});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JPanelLOGO = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtIngresarRfc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPanelBack = new javax.swing.JButton();
        tablaDocentes = new javax.swing.JScrollPane();
        tablaDocentex = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblControl = new javax.swing.JLabel();
        lblNombreAlumno = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblProyecto = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtRfcDoc = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JLabel();
        txtTelefonoDoc = new javax.swing.JLabel();
        ProyectoDoc = new javax.swing.JLabel();
        CorreoDoc1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnEditarDocentes = new javax.swing.JButton();
        btnAgregarDocente = new javax.swing.JButton();
        btnEliminarDocente = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        JPanelLOGO.setBackground(new java.awt.Color(255, 255, 255));
        JPanelLOGO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPanelLOGO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(229, 231, 235));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("BUSCAR CON RFC");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIngresarRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresarRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("GESTIÓN DE DOCENTES");

        JPanelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backbutton.png"))); // NOI18N
        JPanelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanelBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanelLOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelLOGO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaDocentes.setBackground(new java.awt.Color(229, 231, 235));
        tablaDocentes.setBorder(null);
        tablaDocentes.setToolTipText("");
        tablaDocentes.setAutoscrolls(true);
        tablaDocentes.setName(""); // NOI18N

        tablaDocentex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "NOMBRE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaDocentex.setSelectionBackground(new java.awt.Color(0, 83, 188));
        tablaDocentex.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaDocentex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDocentexMouseClicked(evt);
            }
        });
        tablaDocentes.setViewportView(tablaDocentex);

        jPanel2.setBackground(new java.awt.Color(229, 231, 235));

        lblControl.setText("           RFC");

        lblNombreAlumno.setText("Nombre completo");

        lblTelefono.setText("Telefono");

        lblProyecto.setBackground(new java.awt.Color(229, 231, 235));
        lblProyecto.setForeground(new java.awt.Color(229, 231, 235));
        lblProyecto.setText("Proyecto");

        lblCorreo.setText("Correo electronico");

        txtRfcDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombreCompleto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelefonoDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ProyectoDoc.setBackground(new java.awt.Color(229, 231, 235));
        ProyectoDoc.setOpaque(true);

        CorreoDoc1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAlumno)
                            .addComponent(lblControl)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblTelefono))
                            .addComponent(lblCorreo)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblProyecto)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRfcDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTelefonoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CorreoDoc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProyectoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblControl)
                    .addComponent(txtRfcDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCompleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreAlumno))
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefono))
                    .addComponent(txtTelefonoDoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorreo)
                    .addComponent(CorreoDoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProyectoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProyecto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DATOS DEL DOCENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        btnEditarDocentes.setBackground(new java.awt.Color(0, 83, 188));
        btnEditarDocentes.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDocentes.setText("Editar");
        btnEditarDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDocentesActionPerformed(evt);
            }
        });

        btnAgregarDocente.setBackground(new java.awt.Color(0, 83, 188));
        btnAgregarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDocente.setText("Agregar");
        btnAgregarDocente.setActionCommand("");
        btnAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocenteActionPerformed(evt);
            }
        });

        btnEliminarDocente.setBackground(new java.awt.Color(0, 83, 188));
        btnEliminarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDocente.setText("Eliminar");
        btnEliminarDocente.setActionCommand("");
        btnEliminarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarDocenteMouseClicked(evt);
            }
        });
        btnEliminarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnEditarDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnAgregarDocente)
                .addGap(54, 54, 54)
                .addComponent(btnEliminarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(529, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 29, Short.MAX_VALUE)
                    .addComponent(tablaDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditarDocentes)
                    .addComponent(btnAgregarDocente)
                    .addComponent(btnEliminarDocente))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 111, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tablaDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 42, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarPanelLateral(DocenteCarg datos) {
    txtNombreCompleto.setText(datos.getNombre() + " " + datos.getApellidoPaterno() + " " + datos.getApellidoMaterno());
    txtTelefonoDoc.setText(datos.getTelefono());
    CorreoDoc1.setText(datos.getCorreo());
    txtRfcDoc.setText(datos.getRfc());
    ProyectoDoc.setText("En desarrollo");
    }    private void filtrarRFC() {
    String input = txtIngresarRfc.getText().trim().toUpperCase();

    if (input.isEmpty()) {
        limpiarPanelDocente();
        actualizarTablaDocentes(); // ¡Ya tienes este método!
        return;
    }

    List<DocenteCarg> coincidencias = new DocenteDAO().consultarPorRFCParcial(input);
    DefaultTableModel modelo = (DefaultTableModel) tablaDocentex.getModel();
    modelo.setRowCount(0);

    if (!coincidencias.isEmpty()) {
        for (DocenteCarg d : coincidencias) {
            String nombreCompleto = d.getNombre() + " " + d.getApellidoPaterno() + " " + d.getApellidoMaterno();
            modelo.addRow(new Object[]{d.getRfc(), nombreCompleto});
        }
        seleccionarDocenteEnTabla(coincidencias.get(0).getRfc()); // primera coincidencia
    } else {
        limpiarPanelDocente();
    }
}

    private void restaurarTablaDocentes() {
    List<DocenteCarg> listaCompleta = new DocenteDAO().consultarTodos();

    DefaultTableModel modelo = (DefaultTableModel) tablaDocentex.getModel();
    modelo.setRowCount(0); // 🧹 Limpiar tabla

    for (DocenteCarg d : listaCompleta) {
        modelo.addRow(new Object[]{
            d.getRfc(),
            d.getNombre(),
            d.getApellidoPaterno(),
            d.getApellidoMaterno(),
            d.getTelefono(),
            d.getCorreo()
        });
    }
}

    private void limpiarPanelDocente() {
    txtNombreCompleto.setText("");
    txtTelefonoDoc.setText("");
    CorreoDoc1.setText("");
    txtRfcDoc.setText("");
    ProyectoDoc.setText("");
}

    private void seleccionarDocenteEnTabla(String numeroControl) {
    for (int i = 0; i < tablaDocentex.getRowCount(); i++) {
        String valor = tablaDocentex.getValueAt(i, 0).toString();
        if (valor.equals(numeroControl)) {
            tablaDocentex.setRowSelectionInterval(i, i);
            tablaDocentex.scrollRectToVisible(tablaDocentex.getCellRect(i, 0, true));
            return;
        }
        }
        }
    private void tablaDocentexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDocentexMouseClicked
        int filaVisual = tablaDocentex.getSelectedRow();
        if (filaVisual == -1) return;

        int filaModelo = tablaDocentex.convertRowIndexToModel(filaVisual);
        String seleccionRfc = tablaDocentex.getModel().getValueAt(filaModelo, 0).toString();

        DocenteCarg datos = new DocenteDAO().consultarPorRFC(seleccionRfc);
        if (datos == null) return;

        txtNombreCompleto.setText(datos.getNombre() + " " + datos.getApellidoPaterno() + " " + datos.getApellidoMaterno());
        txtTelefonoDoc.setText(datos.getTelefono());
        CorreoDoc1.setText(datos.getCorreo());
        txtRfcDoc.setText(datos.getRfc());
        ProyectoDoc.setText("Sin asignar");
    }//GEN-LAST:event_tablaDocentexMouseClicked

    private void btnEditarDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDocentesActionPerformed
       int filaVisual = tablaDocentex.getSelectedRow();
        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un docente para editar.");
            return;
        }

        int filaModelo = tablaDocentex.convertRowIndexToModel(filaVisual);
        String numeroControl = tablaDocentex.getModel().getValueAt(filaModelo, 0).toString();

        DocenteCarg datos = new DocenteDAO().consultarPorRFC(numeroControl);
        if (datos == null) {
            JOptionPane.showMessageDialog(this, "❌ No se pudo cargar el docente.");
            return;
        }

        EditarDocente editar = new EditarDocente(this);
        editar.cargarDatos(datos.getRfc(), datos.getNombre(), datos.getApellidoPaterno(),
            datos.getApellidoMaterno(), datos.getTelefono(), datos.getCorreo());
        editar.setVisible(true);
        editar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnEditarDocentesActionPerformed

    private void btnAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocenteActionPerformed
         AgregarDocente agregar = new AgregarDocente();
        agregar.setVisible(true);
        agregar.setLocationRelativeTo(null);
        agregar.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                actualizarTablaDocentes();
            }
        });
    }//GEN-LAST:event_btnAgregarDocenteActionPerformed

    private void btnEliminarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDocenteMouseClicked
        int filaVisual = tablaDocentex.getSelectedRow();
        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Selecciona un docente para eliminar.");
            return;
        }

        int filaModelo = tablaDocentex.convertRowIndexToModel(filaVisual);
        String rfc = tablaDocentex.getModel().getValueAt(filaModelo, 0).toString();
        String nombre = txtNombreCompleto.getText();

        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Deseas eliminar a " + nombre + " con RFC " + rfc + "?",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            boolean eliminado = new DocenteDAO().eliminarDocente(rfc);
            if (eliminado) {
                JOptionPane.showMessageDialog(this, "✅ Docente eliminado correctamente.");
                actualizarTablaDocentes();
                txtNombreCompleto.setText("");
                txtTelefonoDoc.setText("");
                CorreoDoc1.setText("");
                txtRfcDoc.setText("");
                ProyectoDoc.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo eliminar al docente.");
            }
        }
    }//GEN-LAST:event_btnEliminarDocenteMouseClicked

    private void btnEliminarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDocenteActionPerformed

    }//GEN-LAST:event_btnEliminarDocenteActionPerformed

    private void JPanelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPanelBackActionPerformed
         Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_JPanelBackActionPerformed
    private void ajustarVentana() {
    java.awt.Window ventana = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (ventana instanceof javax.swing.JFrame) {
        ((javax.swing.JFrame) ventana).pack();
        ventana.setLocationRelativeTo(null);
    }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorreoDoc1;
    private javax.swing.JButton JPanelBack;
    private javax.swing.JPanel JPanelLOGO;
    private javax.swing.JLabel ProyectoDoc;
    private javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnEditarDocentes;
    private javax.swing.JButton btnEliminarDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblControl;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblProyecto;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JScrollPane tablaDocentes;
    public javax.swing.JTable tablaDocentex;
    private javax.swing.JTextField txtIngresarRfc;
    private javax.swing.JLabel txtNombreCompleto;
    private javax.swing.JLabel txtRfcDoc;
    private javax.swing.JLabel txtTelefonoDoc;
    // End of variables declaration//GEN-END:variables
}
