/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.DAO.AlumnoCarg;
import Modelo.DAO.AlumnoDAO;
import Controlador.AcomodarImagen;
import Modelo.DAO.EmpresaDAO;
import Modelo.DAO.ProyectoDAO;
import Modelo.Entidades.Anteproyecto;
import Modelo.Entidades.EmpresaEntidad;
import Modelo.Entidades.Proyecto;
import Utilidades.Conexion;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yahir
 */
public class OpcionAnteproyecto extends javax.swing.JPanel {
private final AcomodarImagen acomodarImagen = new AcomodarImagen();
    CardLayout card;
    private JPanel panelContainer;

    /**
     * Creates new form OpcionAnteproyecto
     */
    public OpcionAnteproyecto(CardLayout layout, JPanel container) {
        super();
        this.setOpaque(false);
        this.card = layout;
    this.panelContainer = container;
    this.setPreferredSize(new Dimension(1000, 650));
     this.card = layout;
        this.panelContainer = container;
        initComponents();
        actualizarTablaAnteproyectos();
        acomodarImagen.configurarPanelConImagen("/img/ITOlogo.png", LogoTec);  
    LogoTec.setOpaque(false);
    LogoTec.setBorder(null);
    LogoTec.setBackground(new Color(0,0,0,0));
    ImageIcon iconoOriginal = new ImageIcon(getClass().getResource("/img/backbutton.png"));
        Image imagenRedimensionada = iconoOriginal.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        JPanelBack.setIcon(new ImageIcon(imagenRedimensionada));
        JPanelBack.setBorderPainted(false);
        JPanelBack.setContentAreaFilled(false);
        JPanelBack.setFocusPainted(false);     
        JPanelBack.setOpaque(false);
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground()); // Usa el color del fondo configurado
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // Radio de redondeo
        g2.dispose();
    }
    public OpcionAnteproyecto() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoTec = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPanelBack = new javax.swing.JButton();
        btnNewAnteproyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAlumnosAnteproyectos = new javax.swing.JTable();
        BtnEditarAnteproyecto = new javax.swing.JButton();
        BtnDetallesAnteproyecto = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        LogoTec.setBackground(new java.awt.Color(255, 255, 255));
        LogoTec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LogoTec.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Anteproyectos");

        JPanelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backbutton.png"))); // NOI18N
        JPanelBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPanelBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoTec, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelBack, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNewAnteproyecto.setBackground(new java.awt.Color(0, 153, 255));
        btnNewAnteproyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnNewAnteproyecto.setText("Nuevo Anteproyecto");
        btnNewAnteproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewAnteproyectoMouseClicked(evt);
            }
        });

        TablaAlumnosAnteproyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaAlumnosAnteproyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAlumnosAnteproyectosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAlumnosAnteproyectos);

        BtnEditarAnteproyecto.setBackground(new java.awt.Color(0, 153, 255));
        BtnEditarAnteproyecto.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditarAnteproyecto.setText("Editar");
        BtnEditarAnteproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarAnteproyectoMouseClicked(evt);
            }
        });

        BtnDetallesAnteproyecto.setBackground(new java.awt.Color(0, 153, 255));
        BtnDetallesAnteproyecto.setForeground(new java.awt.Color(255, 255, 255));
        BtnDetallesAnteproyecto.setText("Ver más");
        BtnDetallesAnteproyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDetallesAnteproyectoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewAnteproyecto)
                        .addGap(83, 83, 83)
                        .addComponent(BtnDetallesAnteproyecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(BtnEditarAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEditarAnteproyecto)
                    .addComponent(btnNewAnteproyecto)
                    .addComponent(BtnDetallesAnteproyecto))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTablaAlumnos(JTable tablaAlumnos) {
         AlumnoDAO dao = new AlumnoDAO();
        List<AlumnoCarg> lista = dao.obtenerTodosLosAlumnos();
        DefaultTableModel model = (DefaultTableModel) tablaAlumnos.getModel();
        model.setRowCount(0);

        for (AlumnoCarg a : lista) {
            String nombreCompleto = a.getNombre() + " " + a.getApellidoPaterno() + " " + a.getApellidoMaterno();
            model.addRow(new Object[]{a.getNumeroControl(), nombreCompleto});
        }
    }
    private void JPanelBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPanelBackActionPerformed
       Window ventana = SwingUtilities.getWindowAncestor(this);
        if (ventana != null) ventana.dispose();
    }//GEN-LAST:event_JPanelBackActionPerformed
public void actualizarTablaAnteproyectos() {
{
    DefaultTableModel model = (DefaultTableModel) TablaAlumnosAnteproyectos.getModel();
    model.setRowCount(0);

    String sql = "SELECT nombre, estado, statusant FROM anteproyecto";

    try (Connection conn = Conexion.getConexion();
         PreparedStatement ps = conn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String nombre = rs.getString("nombre");
            String estado = rs.getString("estado");
            String statusant = rs.getString("statusant");

            model.addRow(new Object[]{nombre, estado, statusant});
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "❌ Error al cargar anteproyectos: " + e.getMessage());
    
}}}
     
    private void btnNewAnteproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewAnteproyectoMouseClicked
         JFrame ventanaAgregar = new JFrame();
        ventanaAgregar.setUndecorated(true);
    AgregarAnteproyecto panelAgregarA = new AgregarAnteproyecto(this);
    ventanaAgregar.setContentPane(panelAgregarA);
    ventanaAgregar.setSize(970,700); //ancho - largo
    ventanaAgregar.setLocationRelativeTo(null); 
    ventanaAgregar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    ventanaAgregar.setVisible(true);

    // Al cerrar, actualizar tabla
    ventanaAgregar.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
        }
    });
    }//GEN-LAST:event_btnNewAnteproyectoMouseClicked

    private void TablaAlumnosAnteproyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAlumnosAnteproyectosMouseClicked
    {
    int filaModelo = TablaAlumnosAnteproyectos.convertRowIndexToModel(TablaAlumnosAnteproyectos.getSelectedRow());

    if (filaModelo != -1) {
        int idAnteproyecto = Integer.parseInt(
            TablaAlumnosAnteproyectos.getModel().getValueAt(filaModelo, 0).toString()
        );

        Anteproyecto ap = new ProyectoDAO().obtenerAnteproyectoPorId(idAnteproyecto);
        EmpresaEntidad empresa = (ap != null) ? new EmpresaDAO().obtenerEmpresaPorRFC(ap.getRfcEmpresa()) : null;

}}
    }//GEN-LAST:event_TablaAlumnosAnteproyectosMouseClicked

    private void BtnEditarAnteproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarAnteproyectoMouseClicked
        JFrame ventanaEditar = new JFrame();
        ventanaEditar.setUndecorated(true);
        EditarAnteproyecto panelEditarA = new  EditarAnteproyecto();
        ventanaEditar.setContentPane(panelEditarA);
        ventanaEditar.setSize(970,700); //ancho - largo
        ventanaEditar.setLocationRelativeTo(null);
        ventanaEditar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaEditar.setVisible(true);

        // Al cerrar, actualizar tabla
        ventanaEditar.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
            }
        });
    }//GEN-LAST:event_BtnEditarAnteproyectoMouseClicked

    private void BtnDetallesAnteproyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDetallesAnteproyectoMouseClicked
        int fila = TablaAlumnosAnteproyectos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un anteproyecto.");
            return;
        }
    }//GEN-LAST:event_BtnDetallesAnteproyectoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDetallesAnteproyecto;
    private javax.swing.JButton BtnEditarAnteproyecto;
    private javax.swing.JButton JPanelBack;
    private javax.swing.JPanel LogoTec;
    private javax.swing.JTable TablaAlumnosAnteproyectos;
    private javax.swing.JButton btnNewAnteproyecto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
